app:
  name: Fortipay
  version: 1.0.0
  environment: development
  time_zone: "Asia/Jakarta"

server:
  port: 8080
  version: /api/v1
  rate_limiter:
    enabled: true
    limit: 100
    duration: 1m

database:
  driver: postgres
  host: 127.0.0.1
  port: 5432
  user: postgres
  password: postgres
  dbname: ngewarung
  sslmode: disable
  max_connection: 300
  max_idle: 300
  max_life_time: "5m"
  max_idle_time: "5m"

rabbitmq:
  host: 127.0.0.1
  port: 5672
  driver: amqp
  user: guest
  password: guest

redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  type: token

logging:
  level: info
  format: json

token: 
  jwt_key: fortipay!321
  signature_key: speskilltest
